# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='计算机名')),
                ('assert_number', models.CharField(max_length=100, unique=True, verbose_name='资产编号')),
                ('cpu', models.CharField(max_length=100, verbose_name='CPU')),
                ('memory', models.CharField(max_length=100, verbose_name='内存')),
                ('ipaddress', models.GenericIPAddressField(verbose_name='IP地址')),
                ('purchase_time', models.DateField(blank=True, null=True, verbose_name='采购日期')),
                ('purpose', models.CharField(max_length=100, verbose_name='用途')),
                ('remarks', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注信息')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部门')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='部门邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='EditHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelname', models.CharField(max_length=100, verbose_name='修改模型')),
                ('item', models.CharField(max_length=100, verbose_name='修改条目')),
                ('context', models.TextField(max_length=1000, verbose_name='修改内容')),
                ('editTime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'ordering': ['-editTime'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='品牌')),
            ],
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=100, verbose_name='操作系统')),
            ],
        ),
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='服务器名')),
                ('ipaddress', models.GenericIPAddressField(verbose_name='IP地址')),
                ('assert_number', models.CharField(max_length=100, verbose_name='资产编号')),
                ('mmodel', models.CharField(max_length=100, verbose_name='型号')),
                ('serial', models.CharField(max_length=100, verbose_name='序列号')),
                ('purchase_time', models.DateField(verbose_name='采购日期')),
                ('purpose', models.CharField(max_length=100, verbose_name='用途')),
                ('remarks', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注信息')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Manufacturer', verbose_name='品牌')),
                ('os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.OS', verbose_name='操作系统')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('tel', models.CharField(max_length=11, verbose_name='联系电话')),
                ('email', models.EmailField(help_text='邮箱地址', max_length=254)),
                ('ipaddress', models.GenericIPAddressField(verbose_name='IP地址')),
                ('entrydata', models.DateTimeField(verbose_name='入职日期')),
                ('computer', models.ManyToManyField(blank=True, null=True, related_name='staffs', to='polls.Computer', verbose_name='主机信息')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Department', verbose_name='所属部门')),
            ],
            options={
                'ordering': ['ipaddress'],
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=100, verbose_name='区域')),
            ],
        ),
        migrations.AddField(
            model_name='servers',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Staff', verbose_name='管理员'),
        ),
        migrations.AddField(
            model_name='servers',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Status', verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='servers',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Zone', verbose_name='所属区域'),
        ),
        migrations.AddField(
            model_name='computer',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Manufacturer', verbose_name='品牌'),
        ),
        migrations.AddField(
            model_name='computer',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.OS', verbose_name='操作系统'),
        ),
        migrations.AddField(
            model_name='computer',
            name='staff',
            field=models.ManyToManyField(blank=True, null=True, related_name='computers', to='polls.Staff', verbose_name='使用人员'),
        ),
        migrations.AddField(
            model_name='computer',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Status', verbose_name='状态'),
        ),
        migrations.AlterUniqueTogether(
            name='staff',
            unique_together=set([('name', 'ipaddress')]),
        ),
    ]
