# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_staff', to='polls.Department', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, help_text='邮箱地址', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='entrydata',
            field=models.DateTimeField(blank=True, null=True, verbose_name='入职日期'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='ipaddress',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='tel',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='联系电话'),
        ),
    ]
