# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170621_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computer',
            name='staff',
        ),
        migrations.AlterField(
            model_name='staff',
            name='computer',
            field=models.ManyToManyField(blank=True, null=True, to='polls.Computer', verbose_name='主机信息'),
        ),
    ]
