# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 01:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170622_0142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='computer',
            new_name='computers',
        ),
    ]
