# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-22 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170622_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='staffs',
            field=models.ManyToManyField(blank=True, null=True, to='polls.Staff', verbose_name='使用人员'),
        ),
    ]
